Add ReSpec template for specification.
w3c-ccg/vc-verifier-http-api pull request #14
Opened 2020-03-15 19:54 UTC by msporny

This PR adds a ReSpec file and various supporting files in preparation for marking up the API in an accepted W3C format.

It's a bit of a failed attempt... doesn't look like the Swagger rendering is going to be compatible with ReSpec (for a variety of Javascript-y and markup reasons). So, there is a separate api.html file that can be used to view the Swagger file as HTML... and the ReSpec document will eventually normatively define the API.

2020-03-15 20:23 UTC, OR13 commented
I'm opposed to doing this separately from the issuer api... 

Managing 2 swagger and 2 respec definitions 2 sets of issues and 2 sets of pull requests is already hitting my pain tolerance threshold :)

Let's discuss what it would take to get these things merged into 1 repo, here:

https://github.com/w3c-ccg/vc-issuer-http-api/issues/26

2020-03-15 20:24 UTC, OR13 requested changes
I'd prefer not to have to duplicate this kind of thing, see the issue regarding merging the specs.

2020-03-16 03:36 UTC, OR13 commented
I was able to get this working the way I wish we had things... 

https://github.com/OR13/respec-swagger
https://or13.github.io/respec-swagger/

1 spec file (index.html)
1 api.yml
1 README
1 repo....

2020-03-16 20:39 UTC, msporny commented
> I was able to get this working the way I wish we had things...

ReSpec bugs being thrown, same issue with this PR... just a FYI -- the Swagger Javascript stuff and the ReSpec Javascript stuff is incompatible. We'll have to figure it out, but +1 to merging the two specs.

2020-03-16 21:09 UTC, OR13 commented
@msporny which bug are you referring too? I'm not seeing any console errors and both respec and swagger appear to be rendering... can you screenshot?

2020-03-16 21:21 UTC, msporny commented
> @msporny which bug are you referring too? I'm not seeing any console errors and both respec and swagger appear to be rendering... can you screenshot?

![ERROR-VCHTTPAPIv0 4-or13 github io](https://user-images.githubusercontent.com/108611/76800680-8fa0c200-67aa-11ea-9ea1-d13877609e22.png)

2020-03-16 22:09 UTC, OR13 commented
hmm seems like iframe and 2 files is probably the best solution. does respec allow use of iframe for rendering things?

2020-03-30 21:19 UTC, OR13 commented
I suggest we close this PR, and address this when we merge these into a single repo.

2020-06-10 17:01 UTC, OR13 commented
I am closing this PR, we need to merge the specs.

2020-06-10 17:01 UTC, closed without merging